### ISSUE TITLE
Save display selection in cookies

### ISSUE THREAD

**Issue by nadangergeo** [nadangergeo/RWD-Table-Patterns#13]
Idea:
- When a user hide/shows a column, save that to cookies
- Load state on init
- only explicitly hidden/shown columns are saved/loaded in the state

**Comment by theBaffo** [comment]
Any progress on this? I'm very interested in this functionality!

**Comment by RafaelRViana** [comment]
+1

**Comment by Oxicode** [comment]
+1

**Comment by grizzlylab** [comment]
+1
