### ISSUE TITLE
Sticky table header does not work in iOS 8

### ISSUE THREAD

**Issue by nadangergeo** [nadangergeo/RWD-Table-Patterns#20]
This is due to the new way iOS Safari handles scroll event. We are working on a new solution.

**Comment by nicmare** [comment]
hope to see a fix soon!

**Comment by nadangergeo** [comment]
I just pushed a potential fix to the **dev branch** (which also contains other untested work). I tested the solution real quick and it seems like it might do the trick for now.

**Comment by nicmare** [comment]
thanks. i will give it a try. you know position: sticky? its an exclusive value for ios (safari) which works like a charm! consider using this as a native sticky element in ios.

**Comment by nadangergeo** [comment]
No problem :) Yeah, I knew about position:sticky before it was released ;) The plan was to implement position:sticky in a future release… unfortunately, I haven’t had time to give this repo some love in the past year (hopefully, I will have more time this year).

Until then, feel free to have a go at it! :)

Hälsningar,
Nadan Gergeo

**Comment by nadangergeo** [comment]
Oh, I just realized why I couldn't use sticky! It would work well with the scroll of the overflown table.

**Comment by nicmare** [comment]
shit :/

**Comment by nicmare** [comment]
alright. i tested the dev branch. it is not perfect but works better than before!! i keep that file. thank you

**Comment by nadangergeo** [comment]
I would suggest that you implement the fix to the master repo instead. I’m not sure how stable the dev branch is.


Hälsningar,
Nadan Gergeo
