### ISSUE TITLE
Hidden and not in checkbox list - enhancement

### ISSUE THREAD

**Issue by Deety** [nadangergeo/RWD-Table-Patterns#21]
I added a -1 data-priority that starts off hidden, but still adds the column header to the checkbox list.
It was just a CSS hack hiding anything with a data-priority of -1, but it seems like a nice feature. I also added a -2 that is hidden and not on the checkbox pulldown. 

Just a thought for future versions.

Another thought for future versions is a the ability to group columns so that they can be switched on and off together. If I come up with a way of doing it, I'll let you know (it'll probably involve adding a data-priority of 'A' or 'B', etc, to several columns, and using the data-col-name of the first item as the entry on the pull down).  Then all I need to do is figure out a way of initiating a sort on the newly made visible column, if some other attribute is set....

Ooh, that's another idea for a future version....sorting!

All in all, though, this is the best starting point I've seen for responsive grids on the net. And I've had a look at a lot! Your code is very good, and easy to follow.

Deb

**Comment by nadangergeo** [comment]
In case you are still interested, this has now been implemented :)

Priority 0 for hidden per default
-1 for hidden and untoggable
