### ISSUE TITLE
add support for semantic-ui.com ?

### ISSUE THREAD

**Issue by quasiperfect** [nadangergeo/RWD-Table-Patterns#23]
hi

first thanks for your work

would this be hard to adapt to work with semantic-ui (semantic-ui.com) ?

**Comment by nadangergeo** [comment]
You're welcome! :)

It shouldn't be that hard to switch out the components used. But I don't have the time to support anything than bootstrap right now. As mentioned in the readme/docs: "If you don't want to use bootstrap, just fork the repo and customize it to your needs!".

Cheers!
