### ISSUE TITLE
Sticky header broken in IE 10/11

### ISSUE THREAD

**Issue by steveszc** [nadangergeo/RWD-Table-Patterns#25]
In IE 10 and 11 the sticky header is not displaying properly. 
The sticky header gets cut off at an arbitrary point. The issue seems to be directly related to the position:fixed property, as the issue goes away if you toggle off the position:fixed property. This is impacting the demo site table as well as custom implementations using this repo.

**Comment by nicmare** [comment]
Did you add the html classes?
```
<!--[if lt IE 7 ]> <html lang="en" class="no-js lt-ie10 lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js lt-ie10 lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js lt-ie10 lt-ie9"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js lt-ie10"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"> <!--<![endif]-->
```

**Comment by steveszc** [comment]
Per my original issue, it is effecting the demo site http://gergeo.se/RWD-Table-Patterns/

If I pull up the demo site in IE11 using Browserstack the sticky header gets cut off. 
See screenshots... the Ipsum header gets cutoff in the sticky header. 


![ie11](https://cloud.githubusercontent.com/assets/6877934/12175454/9562de86-b51f-11e5-8437-ccdb1de9362d.jpg)
![ie11-cutoff](https://cloud.githubusercontent.com/assets/6877934/12175458/99b1aab2-b51f-11e5-9505-4c121960bc50.jpg)

**Comment by nadangergeo** [comment]
Oh lord, Internet Explorer <3

This buggles my mind. It seems to work when position:relative; is removed from .table-responsive[data-pattern="priority-columns"]. I can't recall why position:relative; was important right now... The fix probably needs to be specific for IE, and it needs to be tested.

![screen shot 2016-03-03 at 21 27 42](https://cloud.githubusercontent.com/assets/407621/13509319/17db4dde-e18b-11e5-88e6-e669c68adc43.png)

**Comment by nadangergeo** [comment]
I pushed a potential fix to dev :) I'm not sure how stable dev is, it was a long time ago that we worked on this repo. The dev repo, however, contains fixes and a bunch of refactoring. Hopefully, we will have time to test it soon. You guys could test the dev branch if you'd like, it would help :)

**Comment by nicmare** [comment]
one question/hint regarding the sticky header. did you ever consider using tether lib? it's what they use in bootstrap4. see http://tether.io/
maybe it may help to get this sticky feature work across all devices?!

**Comment by nadangergeo** [comment]
Sticky is a tricky business in this case ^^ The logic of how the sticky header works is tightly coupled with how the table works.

Al though this library has seen better days, it should work *more or less* in all browsers, even ie8. It just needs a bit of love and optimization, that's all.

I've actually been thinking about trying to rewrite the beast as a web component (with or without react, dunno yet).

**Comment by nadangergeo** [comment]
Forgot to mention that this has been fixed in master as of release 5.2.1 😊

**Comment by nicmare** [comment]
yes it works better indeed. thank you! but not perfect. especially if you move the table on x axis (when there is a complex and wide table). i am testing on iphone7. therefore i thought it might be an option to implement tether for these tasks. just a suggestion…

**Comment by nadangergeo** [comment]
It's working ok on IOS for me. Only thing bothering me is that there's a sliiiight delay of the sticky moving when scrolling around (ergo the needed optimization). Is that the problem you are referring to, or?

**Comment by nicmare** [comment]
all in all it works well. there are slightly jumpy moments and it sticks a little bit late (after scrolling has finished). Here is a screencast:
https://www.dropbox.com/sc/uq4jctxqz3zp2dj/AABWDQm26hQu9Z3TReDT2Whta
