### ISSUE TITLE
translate options for focus and display labels

### ISSUE THREAD

**Issue by nicmare** [nadangergeo/RWD-Table-Patterns#27]
i would like to translate "Focus" and "Display" Buttons. And even would like to add a "title" attribute to the link element. please add options for that :+1:

**Comment by wolxXx** [comment]
let's see if the pull request will be accepted..

**Comment by wolxXx** [comment]
jepp. was accepted and merged :)

**Comment by nadangergeo** [comment]
Solved by #29
