### ISSUE TITLE
Footer Option?

### ISSUE THREAD

**Issue by herbertmilhomme** [nadangergeo/RWD-Table-Patterns#28]
Html5 Tables have 3 components.

Header, Body, and Footer.

The code revolves around header and body, but completely ignores the footer. It's completely overlooked, and ignored, when modifying columns with js. Not complaining... Just pointing out that, it's lacking a key area. I want to try to help...

**Comment by pluschnikow** [comment]
+1

**Comment by nadangergeo** [comment]
This is al ready solved in the dev-branch :) Any help testing this branch is appreciated! ✌️

Cheers,
Nadan Gergeo
