### ISSUE TITLE
cloning complete table impacts selectors

### ISSUE THREAD

**Issue by wolxXx** [nadangergeo/RWD-Table-Patterns#30]
hi. 
while creating an instance of the responsive table, the whole table is cloned.
if i understand it right, it is used for creating the header of the table. 
so far, so good. 
but the complete body is copied, too. 
in my case the first column contains checkboxes  for selecting single rows. 
selecting the checkboxes (with jquery / vanilla) returns the double amount of checkboxes after instantiating the responsive table. 
is there any other need for the clone? is it possible to just clone the header? is there a way to prevent the duplicated table body? 

thanks in advance. 

kind regards
wolxXx

**Comment by nadangergeo** [comment]
Hi WolxXX,

We have fixed that in the dev branch! Unfortunately, the dev-branch needs more testing before I merge it in. You are more than welcome to help out :)

Best regards,
Nadan Gergeo

**Comment by wolxXx** [comment]
well, you know, girls require more time than awesome open source projects ;) 
i'll be at your side, soon!

**Comment by nadangergeo** [comment]
Hahaha, I know exactly how it is 😄👊

Hälsningar,
Nadan Gergeo
