### ISSUE TITLE
Angular Support

### ISSUE THREAD

**Issue by twilly86** [nadangergeo/RWD-Table-Patterns#31]
I'm having trouble getting this to work with angular tables that are generated using ng-repeat.  I beleive it's a timing issue as angular renders table rows on the fly based on data.

Has anyone gotten this to work?

**Comment by nadangergeo** [comment]
I just released v5.2.0 which includes two new (semi-private) methods which could help you out. (Un)fortunatelly, I have not used angular for a while and I am not sure how to test it out. The API might [read: probably] need some updating.

# setupRow(row, indices)
- Used to set up a newly added row. 
- Row is the row-element to be setup.
- Indices is a mapping between a cells index, and the proper column. It is created by the method buildHeaderCellIndices() and stored in the instance as this.headerColIndices on construction. 

# update()
Run this after the content in tbody/tfoot has changed

**Comment by agronom81** [comment]
Hi!
Thanks for your plugin.
I am having trouble getting this to work with jquery datatables pagination.
I have everything working, but I can not call the method update. Tell me how to do it. Thanks.

**Comment by nadangergeo** [comment]
@agronom81 and @twilly86 Please see my updated answer above :)

**Comment by calebmiracle** [comment]
I had a similar issue working with Aurelia. The update function didn't work for me if the number of rows was different than when the table was originally initialized. At first glance, I think this could be fixed if this.$bodyRows was reinitialized in the update function before calling setupBodyRows.

**Comment by nadangergeo** [comment]
@camiracle Good catch! I just patched it with latest release (v5.2.4) :) Thanks! Let me know if it works. I am quite eager to close this issue ^^

@twilly86 Any update? (pun intended)

**Comment by camiracle** [comment]
5.2.1 is still the latest version I'm seeing. I copied your changes for testing, though, and it works better now with a dynamic number of rows.

There is a remaining issue that I run into if I follow these steps:
- Populate and initialize a new table. For this example, let's say there are 2 rows of data.
- Hide some of the columns via the "Display" dropdown
- Dynamically add more rows to the table
- Call the update method
- **Result**: The headers are still missing for the hidden rows, as well as the data for the first 2 rows. The newly added rows show all data.

Let me know if that doesn't make sense. Thanks for your work on this, and for the plugin, it's pretty sweet.

**Comment by nadangergeo** [comment]
@camiracle Thank you, I'm glad you like it! ^^ I just pushed a new release (v5.2.5) which should solve the issue you described. Let's hope there aren't any more cases that I've missed :D

**Comment by camiracle** [comment]
That seems to be working perfectly, cheers!

**Comment by nadangergeo** [comment]
Woop woop! Nice to hear :D Cheers!

Hälsningar,
Nadan Gergeo
