### ISSUE TITLE
Button Placement

### ISSUE THREAD

**Issue by ryansh100** [nadangergeo/RWD-Table-Patterns#34]
Would be helpful if the display all and display option dropdown could be placed in a target element. Perhaps a [data-table-controls] attribute on the holding element.

**Comment by ryansh100** [comment]
See PR https://github.com/nadangergeo/RWD-Table-Patterns/pull/35

**Comment by ryansh100** [comment]
Is this project still active?

**Comment by nadangergeo** [comment]
Hi Ryan,

Yes, it is still alive, I have just been really busy. Thank you for the PR, I will look at it as soon as possible!

Best regards,
Nadan Gergeo
