### ISSUE TITLE
sortable columns and trigggers

### ISSUE THREAD

**Issue by lapizd** [nadangergeo/RWD-Table-Patterns#39]
This code works awesome! It works very well for a data table I am creating, but is there an easy way to make the columns sortable?

Also, I am planning to have some triggers to open nested tables. I know this will complicate things a little but any feedback or help will be appreciate it.

Thank you!

**Comment by rickydeez** [comment]
+1

**Comment by Mahdi-Ra** [comment]
Does it work with Bootstrap4??

**Comment by nadangergeo** [comment]
Sortable columns added to latest release 👍
