### ISSUE TITLE
Sticky header, but only on one viewport

### ISSUE THREAD

**Issue by Tickthokk** [nadangergeo/RWD-Table-Patterns#43]
Hi!

On my XS viewport I have a sticky header, but on SM+ I do not.  I'm unable to update the config after it's already run.  If a user resizes their browser, they'll be stuck with the configuration from their original viewport.

Here's some (cut up/pseudo) JS I've got.  At this point I've already initialized it and I've detected a viewport change on my end.

```javascript

if (... viewport != xs ...)
	config.fixedNavbar = '.navbar-fixed-top'; // default, doesn't exist

$('.table-responsive').responsiveTable(config);

$('.sticky-table-header').remove();
$('.table-responsive').responsiveTable('createStickyTableHeader');
$('.table-responsive').responsiveTable('update');
```

I've tried this, and things like it, but no luck.  Is there a way to "start fresh" on the same screen?  I don't see a `destroy` function :(

I'd be willing to custom alter the original JS to get what I need (within the resize function), but if there's an official way to do this that'd be great.

Thanks!

**Comment by nadangergeo** [comment]
Have you tried just hiding it with css?

**Comment by Tickthokk** [comment]
But I like it :p

**Comment by nadangergeo** [comment]
Hehe, alright! Good luck! :)
