### ISSUE TITLE
Dynamic content, Call Update() not working!

### ISSUE THREAD

**Issue by itsmekps** [nadangergeo/RWD-Table-Patterns#50]
I am populating the table body with ajax 
```
success:function(response)
{

	$("#students").append(response);  // #students is tbody id (<tbody id="students">)
	$('.table-responsive').responsiveTable('update');
        //$('#the_id_to_the_table_responsive_wrapper').responsiveTable('update');
	console.log(response)
}
```
neither` $('.table-responsive').responsiveTable('update');`  this is working nor `$('#the_id_to_the_table_responsive_wrapper').responsiveTable('update');` 

pls suggest a solution

**Comment by JordanAW545** [comment]
Am also having this issue. Data does not change even though I emptied tbody and repopulated it and calling `('.table-responsive').responsiveTable('update')`. please advise.

**Comment by nadangergeo** [comment]
Sorry for the late answer! Can you guys provide codepen? Update works for me =/

**Comment by JordanAW545** [comment]
Seems like I have found the issue. When we appended to the table body, `$("#students")` selector was retrieving from the clone table. Therefore, it'll be better to use `$("#[table's id] #students")` instead of just selecting the tbody.

**Comment by JordanAW545** [comment]
Alternatively, is it possible to also change the id of the tbody in the cloned table? So as to not add confusion when coding.

**Comment by ErvinCheung** [comment]
[Whether this code is executed in the appropriate options?](https://github.com/nadangergeo/RWD-Table-Patterns/blob/3066664fc406a19a1a8aa00dc69f2369406b5dd0/src/js/rwd-table.js#L632)

> this.options.stickyTableHeader

```
if (this.options.stickyTableHeader) {
            // Remove old tbody clone from Tableclone
            this.$tableClone.find('tbody, tfoot').remove();

            // Make new clone of tbody
            var $tbodyClone = this.$table.find('tbody, tfoot').clone();

            //replace ids
            $tbodyClone.find('[id]').each(function() {
              $(this).prop('id', $(this).prop('id') + '-clone');
            });

            // Append new clone to tableClone
            $tbodyClone.appendTo(this.$tableClone);
        }

```

**Comment by HAGhoniem** [comment]
thanks, @JordanAW545 
your answer helped me to fix this issue

**Comment by BopKrt** [comment]
Hi @HAGhoniem 
could you please explain how you solved the issue with @JordanAW545 's solution? I'm trying to use **$("#[table's id] #students")**.append(htmlcontent) followed by **$('.table-responsive').responsiveTable('update');**, but it's  unsuccessfully´, nothing happens. 

ps: htmlcontent is something like <tr><td>name</td></tr> in order to add more rows.
Thxs (=

**Comment by nadangergeo** [comment]
Hello,
Here is a long overdue working example for the update function that you can try on the demo page.

```javascript
var tableId = "#tech-companies";
var tableWrapperId = "#tech-companies-wrapper";

function cloneAndAppendRows(tableId) {
  // Clone the last 10 'tr' elements
  var $clonedRows = $(tableId + ' tr').slice(-10).clone();

  // Remove 'data-' attributes from 'tr', 'td', and 'th' elements within the cloned rows
  $clonedRows.find('td, th').addBack('tr').each(function() {
    var $this = $(this); // Cache the current jQuery object
    var dataAttrs = $.map(this.attributes, function(attribute) {
      // Check if the attribute name starts with 'data-'
      return attribute.name.startsWith('data-') ? attribute.name : null;
    });
    // Remove each 'data-' attribute
    $.each(dataAttrs, function(i, attrName) {
      $this.removeAttr(attrName);
    });
  });

  // Append the cleaned cloned rows to the end of the table
  $(tableId).append($clonedRows);
}

// Call the cloning function with the table ID 'tech-companies'
cloneAndAppendRows(tableId);

// Call update method
// Try without this step to see the difference!
$(tableWrapperId).responsiveTable('update');
//('.table-responsive').responsiveTable('update'); // also works, same result
//$(tableId).parent().responsiveTable('update'); // also works, same result
```
